# Creating and saving NdArrays


In [2]:
# import numpy into python
import numpy as np

# Create 1D ndarray using array() function
x = np.array([1, 2, 3, 4, 5])

# print the array
print("x = ", x)

x =  [1 2 3 4 5]


Determine the shape and dtype of the nd array

In [6]:
print("x has dimensions  :  ", x.shape)
print("type of x is  :  ", type(x))
print("Elements of x are of type: ", x.dtype)

x has dimensions  :   (5,)
type of x is  :   <class 'numpy.ndarray'>
Elements of x are of type:  int32


Datatypes supported by Numpy: https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html


In [8]:
x = np.array(['Hello','World','veronica'])
print(x, "\n")
print("x has dimensions  :  ", x.shape)
print("type of x is  :  ", type(x))
print("Elements of x are of type: ", x.dtype)

['Hello' 'World' 'veronica'] 

x has dimensions  :   (3,)
type of x is  :   <class 'numpy.ndarray'>
Elements of x are of type:  <U8


Here, shape of x were (5,) and (2,) indicating that it is a 1D array or rank 1 vector. the data type U5 indicates that the elements are unicode strings with 5 characters.

Difference between python lists and nd arrays is that ndarray can onlu hold elements of the same data type. When we pass in a heterogenous python list to create ndarray, numpy will convert them intp strings and store them as unicode charaters

In [9]:
# create a heterogenous python list
lst = ["wonbderful", 1, 5, 5.630]
x = np.array(lst)
print(x, "\n")
print("x has dimensions  :  ", x.shape)
print("type of x is  :  ", type(x))
print("Elements of x are of type: ", x.dtype)

['wonbderful' '1' '5' '5.63'] 

x has dimensions  :   (4,)
type of x is  :   <class 'numpy.ndarray'>
Elements of x are of type:  <U10


**Multi dimensional array**

In [11]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print(x, "\n")
print("x has dimensions  :  ", x.shape)
print("x has a total of   :  ", x.size, "elements")
print("type of x is  :  ", type(x))
print("Elements of x are of type: ", x.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

x has dimensions  :   (4, 3)
x has a total of   :   12 elements
type of x is  :   <class 'numpy.ndarray'>
Elements of x are of type:  int32


**Upcasting**

NdArray of ints and floast will be stored as float64

In [14]:
# ndarray - ints
x = np.array([1, 2, 3, 4])
print("data type : ", x.dtype)

# ndarray - floats
x = np.array([1.3, 2.6, 3.5, 4.1])
print("data type : ", x.dtype)

# ndarray of ints and floats
x = np.array([9, 7, 3.5, 3])
print("data type : ", x.dtype)

data type :  int32
data type :  float64
data type :  float64


**Saving  and Loading NdArrays**

The arrays are stored ina  file with ".npy" extension

In [19]:
# creata array
x = np.array([1, 2, 3, 4, 5])

# save array into current directory
np.save('my_array', x)

# load the array
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


## 2. Built-in functions to create ndarrays

Note that the input to zeros, ones functions are tuples, so we need two braces (( ))

In [22]:
# np arrays of zeros
x = np.zeros((3, 4))
print(x)
print("dtype: ", x.dtype)

# dtype can be specified while creation
x = np.zeros((3, 4), dtype = int)
print(x)
print("dtype: ", x.dtype)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
dtype:  float64
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
dtype:  int32


In [24]:
# np arrays of ones
x = np.ones((5,6))
print(x)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [26]:
# np array of "constants"
x = np.full((3, 4), 6)
print(x)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


To create identity matrix

In [28]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [30]:
# diag takes sequence of diagonal values
x = np.diag([10, 20, 30, 40 ,50 ])
print(x)

[[10  0  0  0  0]
 [ 0 20  0  0  0]
 [ 0  0 30  0  0]
 [ 0  0  0 40  0]
 [ 0  0  0  0 50]]


**Arange** - start (inclusive), stop(exclusive), step

In [35]:
# arange with only end value
x = np.arange(10)
print(x)

# with start, stop
x = np.arange(4, 10)
print(x)

# with start, stop and step
x = np.arange(1, 15, 3)
print(x)

x = np.arange(1, 15, 21)
print(x)

x = np.arange(1, 15, 0.5)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[4 5 6 7 8 9]
[ 1  4  7 10 13]
[1]
[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5]


**Linspace** - start(inclusive), stop(inclusive), N (number of elements)

Even though arange allows, non-integer steps, its better to use "linspace" to generate that. Linspace creates N evenly spaced number from sttart and stop. N is optional and defaults to 50

In [41]:
# linspace with only start and stop, N = 50 default
x = np.linspace(5, 10)
print(x, "\n")

# start/stop - inclusive
x = np.linspace(0,25,10)
print(x, "\n")

# to make stop - exclusive
x = np.linspace(0,25,10, endpoint = False)
print(x, "\n")


[ 5.          5.10204082  5.20408163  5.30612245  5.40816327  5.51020408
  5.6122449   5.71428571  5.81632653  5.91836735  6.02040816  6.12244898
  6.2244898   6.32653061  6.42857143  6.53061224  6.63265306  6.73469388
  6.83673469  6.93877551  7.04081633  7.14285714  7.24489796  7.34693878
  7.44897959  7.55102041  7.65306122  7.75510204  7.85714286  7.95918367
  8.06122449  8.16326531  8.26530612  8.36734694  8.46938776  8.57142857
  8.67346939  8.7755102   8.87755102  8.97959184  9.08163265  9.18367347
  9.28571429  9.3877551   9.48979592  9.59183673  9.69387755  9.79591837
  9.89795918 10.        ] 

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ] 

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5] 



**Reshape** 

In [44]:
n = np.arange(20)
print(n, "\n")

# shape specified is compatible with number of elements
x = np.reshape(n, (4,5))
print(x, "\n")

x = np.reshape(n, (10, 2))
print(x, "\n")

# shape is bigger than elements
y = np.reshape(n, (4,7))
print(y, "\n")


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] 



ValueError: cannot reshape array of size 20 into shape (4,7)

**Sequence of functions**

In [50]:
y = np.arange(20).reshape(10,2)
print(y,"\n")

y = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)
print(y,"\n")

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]] 

[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]] 



### Random number generation


In [56]:
x = np.random.random((3, 3))
print(x)

# creating random numbers with lower and upper bounds
x = np.random.randint(4, 15, (4, 3))
print(x)

# create random numbers that follows a specific probabilistic distribution
# Gauss, mean=0, std=0.1
x = np.random.normal(0, 0.1, size=(10, 10))
print(x)
print("Mean  : ", x.mean())
print("Std  : ", x.std())
print("Min  : ", x.min())
print("Max  : ", x.max())

[[0.25262346 0.57883962 0.55568759]
 [0.78922629 0.13555888 0.32313149]
 [0.9312649  0.01203429 0.79752608]]
[[14  9 14]
 [14 13  7]
 [ 6  5 12]
 [14 11  6]]
[[ 0.01548837  0.1043768  -0.02415895 -0.1722353   0.12611527  0.04628533
  -0.02850074 -0.01564702  0.15419327 -0.02708173]
 [-0.09068411  0.08592405  0.19344785 -0.02654091  0.08804257  0.11700849
  -0.05231771  0.10645427 -0.00216753 -0.05200637]
 [-0.05293474 -0.1617262   0.0477498   0.15247311 -0.15258493  0.07100371
  -0.03966878 -0.01532675  0.06755106  0.01203431]
 [-0.02987863 -0.00257698 -0.11518819  0.12065814  0.02318771  0.04942506
  -0.17222084 -0.05517042 -0.00708475  0.02271248]
 [ 0.04901843 -0.03406047  0.04310014  0.16881652 -0.12287314 -0.06217675
   0.03317963 -0.03212842  0.17153268  0.03478461]
 [-0.00537916 -0.03703344 -0.06376793  0.15280405  0.06755613  0.10044712
   0.02571165  0.05784171  0.27622971 -0.09885823]
 [ 0.03045065  0.07450244 -0.06976169 -0.01241899  0.07698087 -0.04885786
  -0.1875912   0.0

In [62]:
x = np.linspace(2, 32, 16, dtype=int).reshape(4,4)
print(x)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
