# More NdArray operations

**Boolean Indexing**

In [1]:
import numpy as np

In [6]:
x = np.arange(25).reshape(5,5)
print(x)

print(x[x > 10])

print(x[x <= 8])

print(x[(x > 10) & (x <= 23)])

x[(x > 10) & (x <= 23)] = 100
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[0 1 2 3 4 5 6 7 8]
[11 12 13 14 15 16 17 18 19 20 21 22 23]
[[  0   1   2   3   4]
 [  5   6   7   8   9]
 [ 10 100 100 100 100]
 [100 100 100 100 100]
 [100 100 100 100  24]]


**Set Operations**

In [8]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 2, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


**Sorting**

* out of place - does not change original => np.sort(x)
* in place - changes the original => x.sort()

In [18]:
x = np.random.randint(1,11,size=(10,))
print(x)

# out of place sorting
print(np.sort(x))
print(x)

# sorting only unique elements
print(np.sort(np.unique(x)))

# inplace sorting - affects the original array
x.sort()
print(x)

# sorting 2d arrays
x = np.random.randint(1,11,size=(5,5))
print(x)

print(np.sort(x, axis=0))

print(np.sort(x, axis=1))

[4 8 6 1 8 3 9 8 9 6]
[1 3 4 6 6 8 8 8 9 9]
[4 8 6 1 8 3 9 8 9 6]
[1 3 4 6 8 9]
[1 3 4 6 6 8 8 8 9 9]
[[ 5  3  8  8  8]
 [ 5  2  4 10  5]
 [ 4  2  1  8  4]
 [ 7  4  1  9  8]
 [ 8  7  5  7  1]]
[[ 4  2  1  7  1]
 [ 5  2  1  8  4]
 [ 5  3  4  8  5]
 [ 7  4  5  9  8]
 [ 8  7  8 10  8]]
[[ 3  5  8  8  8]
 [ 2  4  5  5 10]
 [ 1  2  4  4  8]
 [ 1  4  7  8  9]
 [ 1  5  7  7  8]]


In [22]:
# display odd numbers from 1 to 25
x = np.arange(1, 26).reshape(5,5)
print(x[x%2 != 0])

[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


### Arithmetic operations

In [35]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))

# 2d arrays
x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = np.array([5, 6, 7, 8]).reshape(2, 2)

print(x + y)
print(np.add(x, y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x / y)
print(np.divide(x, y))


[ 6  8 10 12]
[ 6  8 10 12]
[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]
[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1 2]
 [3 4]]
[[4 5]
 [6 7]]
[[ 7 14]
 [21 28]]


**Broadcasting**

When we add 3 to a 2d array, numpy broadcasts 3 to the shape of x

In [36]:
# ==== Broadcasting =====
x = np.array([1, 2, 3, 4])
print(x)
print(x + 3)
print(x * 7)

x = np.arange(9).reshape(3,3)
y = np.arange(3)
print(x)
print(y)
print(x + y)

[1 2 3 4]
[4 5 6 7]
[ 7 14 21 28]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [33]:
x = np.array([1, 2, 3, 4])
print(x)

print(np.sqrt(x))

print(np.exp(x))

print(np.power(x, 2))

x = np.array([1, 2, 3, 4]).reshape(2,2)
print(x)

print(np.mean(x))
print(x.mean())
print(x.mean(axis=0))
print(x.mean(axis=1))

print(x.std())

print(x.min())

print(x.max())

#print(x.median()) # This is NOT VALID
print(np.median(x))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 1  4  9 16]
[[1 2]
 [3 4]]
2.5
2.5
[2. 3.]
[1.5 3.5]
1.118033988749895
1
4
2.5


In [44]:
x = np.zeros((4,4), dtype=int) + np.arange(1, 5)
print(x)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
