# Manipulating NdArrays

Numpy arrays are "Mutable", can be changed

In [1]:
import numpy as np

In [6]:
x = np.array([1, 2, 3, 4, 5])

# positive and negative indices
print(x[0])
print(x[1])
print(x[-1])
print(x[-2])
print(x[-4])
print(x[-5])
print(x[-0])

1
2
5
4
2
1
1


Accessing elements:

rank two nd arrays => ndarray[i, j]

In [15]:
x = np.array([1, 2, 3, 4, 5])
x[3] = 20
print(x)

x = np.arange(1,10).reshape(3,3)
print(x)
print("Element at (0,0) : ", x[0, 0])
print("Element at (1,2) : ", x[1, 2])

# modify rank two elements
x[1, 1] = 235
print(x)

[ 1  2  3 20  5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Element at (0,0) :  1
Element at (1,2) :  6
[[  1   2   3]
 [  4 235   6]
 [  7   8   9]]


**Append / Insert / Delete**

Axis=o specifies rows and axis=1 specifies columns

In [25]:
x = np.array([1, 2, 3, 4, 5])
print(x)

# Delete first and last element
x = np.delete(x, [0, 4])
print(x)

# Append values
x = np.append(x, 7)
print(x)

x = np.append(x, [26, 58, 76])
print(x)

# Insert - (input array, position, array to be inserted, axisS)
x = np.insert(x, 0, 100)
print(x)

x = np.insert(x, [1, 4], 200)
print(x)

x = np.insert(x, 2, [50, 51, 52])
print(x)

[1 2 3 4 5]
[2 3 4]
[2 3 4 7]
[ 2  3  4  7 26 58 76]
[100   2   3   4   7  26  58  76]
[100 200   2   3   4 200   7  26  58  76]
[100 200  50  51  52   2   3   4 200   7  26  58  76]


Rank 2 arrays

In [35]:
# ===== Rank 2 arrays =======
x = np.arange(1, 10).reshape(3, 3) 
print(x)

# delete 0th row
x = np.delete(x, 0, axis=0)
print(x)

# delet 0th and last column
x = np.delete(x, [0, 2], axis=1)
print(x)

# Append
x = np.arange(1, 10).reshape(3, 3) 
print(x)

x = np.append(x, [[10, 11, 12]], axis=0)
print(x)
x = np.append(x, [[51], [52], [53], [54]], axis=1)
print(x)

# Insert
x = np.arange(1, 10).reshape(3, 3) 
print(x)

x = np.insert(x, 1, [11, 12, 13], axis=0)
print(x)

x = np.insert(x, 2, [32, 33, 34, 35], axis=1)
print(x)

# insert a column full of 500
x = np.insert(x, 1, 500, axis=1)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]
[[5]
 [8]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3 51]
 [ 4  5  6 52]
 [ 7  8  9 53]
 [10 11 12 54]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [11 12 13]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1  2 32  3]
 [11 12 33 13]
 [ 4  5 34  6]
 [ 7  8 35  9]]
[[  1 500   2  32   3]
 [ 11 500  12  33  13]
 [  4 500   5  34   6]
 [  7 500   8  35   9]]


**Stacking ndarrays**

This assumes the shape of the arrays being stacked match each other.

Note vstack takes input as tuples (( ))

In [43]:
x = np.array([1, 2])
y = np.array([[3, 4], [5, 6]])
v = np.vstack((x, y))
print(v)

h = np.hstack((v, np.array([51, 52, 53]).reshape(3,1)))
print(h)

[[1 2]
 [3 4]
 [5 6]]
[[ 1  2 51]
 [ 3  4 52]
 [ 5  6 53]]


### Slicing the Arrays

starting index (inclusive), ending index(exclusive)

In [53]:
x = np.arange(1, 21).reshape(4, 5)
print(x)

# 4,5 excluded
print(x[1:4, 2:5])

print(x[1:, 2:])

print(x[:3, 2:])

# returns a rank 1 result
print(x[:, 2])

# returns a rank 2 result *
print(x[:, 2:3])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]
[ 3  8 13 18]
[[ 3]
 [ 8]
 [13]
 [18]]


**Copy**

Numpy slicing is changing the mutable array. If we change values in the slice, we change the original too. To prevent this use, numpy.copy


In [55]:
x = np.arange(1, 21).reshape(4,5)
print(x)

z = x[1:, 2:]
print(z)
z[2, 2] = 555;
print(z)
print(x)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 8  9 10]
 [13 14 15]
 [18 19 20]]
[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]
[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]
 [ 16  17  18  19 555]]


In [57]:
# Using Copy()
x = np.arange(1, 21).reshape(4,5)
print(x)

z = np.copy(x[1:, 2:])

# another way
y = x[1:, 2:].copy()

z[2, 2] = 555;
print(z)
print(x)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


**Elements around diagonal**

In [63]:
x = np.diag([10, 20, 30])
print(x)**Unique**

x = np.arange(1, 21).reshape(4,5)
z = np.diag(x)
print(z)

# 1 row above the leading diagonal
print(np.diag(x, k=1))

print(np.diag(x, k=2))

# 1 row below the leading diagonal
print(np.diag(x, k=-1))

print(np.diag(x, k=5))

[[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]
[ 1  7 13 19]
[ 2  8 14 20]
[ 3  9 15]
[ 6 12 18]
[]


**Unique**

In [65]:
x = np.array([[1, 2, 3], [1, 5, 2], [2, 8 ,3]])
print(np.unique(x))

[1 2 3 5 8]


In [100]:
# Create a 1000 x 20 ndarray with random integers in the half-open interval [0, 5001).
X= np.random.randint(0, 5001, (1000, 20))
print(X)

# print the shape of X
print(np.shape(X))

x = np.array([[1, 2],[3, 4]])
y = np.array([[5, 6],[7, 8]])
print(x)
print(y)
print(x-y)
print(np.mean(x, axis=1))
np.shape(x)
x = np.random.permutation(10)
print(x)
print(np.size(x))
print(x[:])
print(x[6:8])
print(x[-2:])

[[ 184 1130 3679 ... 4118 1313 1948]
 [ 889 3332 2355 ... 1384 2156 4297]
 [3058  220  274 ... 2465 4430 3941]
 ...
 [1944 4703  326 ... 1528  803  242]
 [1121 2583 2610 ... 2170 4277 4619]
 [1084 3170 1511 ...  658 3905 1298]]
(1000, 20)
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[-4 -4]
 [-4 -4]]
[1.5 3.5]
[0 7 5 1 9 3 6 8 2 4]
10
[0 7 5 1 9 3 6 8 2 4]
[6 8]
[2 4]
